apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win10-hd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  #storageClassName: hostpath
  storageClassName: d-nfs-sc
