apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win10-hd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  #storageClassName: hostpath
  storageClassName: amerigo-nfs-sc
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: amerigo-win10-vm
  labels:
    kubevirt.io/domain: amerigo-windows
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: amerigo-windows
    spec:
      domain:
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            vapic: {}
            spinlocks:
              spinlocks: 8191    
        cpu:
          cores: 4
        devices:
          autoattachGraphicsDevice: True
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - bootOrder: 2
            cdrom:
              bus: sata
            name: virtiocontainerdisk            
          - bootOrder: 3
            disk:
              bus: virtio
            name: harddrive
        #firmware:
      # this sets the bootloader type
          # bootloader:
          #   efi: {} 
          interfaces:
          - masquerade: {}
            model: e1000e 
            name: default               
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      networks:
        - name: default
          pod: {}              
      volumes:
      - dataVolume:
          name: win10-vm
        name: cdromiso  
      # - name: cdromiso
      #   persistentVolumeClaim:
      #     claimName: win10-vm
      - name: harddrive
        persistentVolumeClaim:
          claimName: win10-hd
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
