apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win10-hd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  #storageClassName: hostpath
  storageClassName: d-nfs-sc
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: d-win10-vm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: d-win10-vm
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 2G
      volumes:
      - dataVolume:
          name: win10-vm
        name: cdromiso  
      # - name: cdromiso
      #   persistentVolumeClaim:
      #     claimName: win10-vm
      - name: harddrive
        persistentVolumeClaim:
          claimName: win10-hd
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk